name: Pull request actions

on:
  pull_request:
    branches: [ develop ]


jobs:
  pull_request_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn test
      - run: mvn clean install -DskipTests